'use strict';
// Bundles the game engine (the same files the server uses) into docs/engine.js so the offline app
// runs identical rules in the browser. Run: npm run build   (npm test fails if engine.js is stale)
const fs = require('fs');
const path = require('path');
const MODULES = ['config', 'blackjack', 'casino', 'wallet', 'tables', 'games-service'];

function build() {
  const parts = MODULES.map((m) => {
    const src = fs.readFileSync(path.join(__dirname, '..', 'lib', m + '.js'), 'utf8');
    return `  './${m}': function (module, exports, require, process) {\n${src}\n  },`;
  });
  return `// GENERATED by scripts/build-engine.js from lib/*.js. Do not edit by hand.
(function () {
  'use strict';
  var webCrypto = window.crypto;
  var cryptoShim = {
    randomInt: function (max) { // unbiased integer in [0, max)
      var limit = Math.floor(4294967296 / max) * max, buf = new Uint32Array(1);
      do { webCrypto.getRandomValues(buf); } while (buf[0] >= limit);
      return buf[0] % max;
    },
    randomUUID: function () { return webCrypto.randomUUID ? webCrypto.randomUUID() : String(Date.now()) + Math.random(); },
  };
  var fakeProcess = { get env() { return window.RB21EngineEnv || {}; } };
  var defs = {
${parts.join('\n')}
  };
  var cache = {};
  function req(name) {
    if (name === 'crypto') return cryptoShim;
    var key = name.replace(/\\.js$/, '');
    if (cache[key]) return cache[key].exports;
    if (!defs[key]) throw new Error('engine: missing module ' + name);
    var module = { exports: {} };
    cache[key] = module;
    defs[key](module, module.exports, req, fakeProcess);
    return module.exports;
  }
  window.RB21Engine = { require: req };
})();
`;
}
const out = path.join(__dirname, '..', 'docs', 'engine.js');
if (process.argv.includes('--check')) {
  if (!fs.existsSync(out) || fs.readFileSync(out, 'utf8') !== build()) { console.error('docs/engine.js is out of date: run npm run build'); process.exit(1); }
  console.log('engine.js up to date');
} else { fs.writeFileSync(out, build()); console.log('wrote docs/engine.js'); }
